# This is the cluster wide security-profiles-operator deployment, which listens for
# configMaps on all namespaces
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base

resources:
  - service.yaml
  - webhook.yaml

patchesJson6902:
  - target:
      version: v1
      kind: ConfigMap
      name: security-profiles-operator-profile
    path: operator-profile.yaml

images:
  - name: gcr.io/k8s-staging-sp-operator/security-profiles-operator
    newName: image-registry.openshift-image-registry.svc:5000/openshift/security-profiles-operator
    newTag: latest

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: security-profiles-operator
    namespace: security-profiles-operator
    annotations:
      service.alpha.openshift.io/serving-cert-secret-name: spo-webhook-tls
  spec:
    template:
      spec:
        containers:
          - name: security-profiles-operator
            args:
            - manager
            - '--enable-webhook'
            env:
              - name: RELATED_IMAGE_OPERATOR
                value: image-registry.openshift-image-registry.svc:5000/openshift/security-profiles-operator:latest
            volumeMounts:
              - name: webhook-tls
                mountPath: /webhook-server/serving-certs
                readOnly: true
        volumes:
          - name: webhook-tls
            secret:
              secretName: spo-webhook-tls