---
apiVersion: v1
kind: Service
metadata:
  name: selinux-namespace-webhook
  namespace: security-profiles-operator
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: spo-webhook-tls
spec:
  selector:
    name: security-profiles-operator
  ports:
    - protocol: TCP
      port: 8443
