---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "selinux-policy-in-pod-namespace.security-profiles-operator.x-k8s.io"
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
webhooks:
- name: "selinux-policy-in-pod-namespace.security-profiles-operator.x-k8s.io"
  failurePolicy: Ignore
  namespaceSelector:
    matchExpressions:
    - key: openshift.io/run-level
      operator: NotIn
      values: ["0","1"]
  rules:
  - apiGroups:   [""]
    apiVersions: ["v1"]
    operations:  ["CREATE", "UPDATE"]
    resources:   ["pods"]
    scope:       "Namespaced"
  clientConfig:
    service:
      namespace: "security-profiles-operator"
      name: "selinux-namespace-webhook"
      path: "/validate-selinuxpolicy-namespace"
      port: 8443
  admissionReviewVersions: ["v1beta1"]
  sideEffects: None
  timeoutSeconds: 3
